android:
- changed-files:
  - any-glob-to-any-file:
    - src/App/*
    - src/Core/*
    - src/Android/*
    - 'src/Xamarin.AndroidX.Credentials/*'

iOS:
- changed-files:
  - any-glob-to-any-file:
    - src/App/*
    - src/Core/*
    - lib/ios/*
    - src/iOS/*
    - 'src/iOS.Autofill/*'
    - 'src/iOS.Core/*'
    - 'src/iOS.Extension/*'
    - 'src/iOS.ShareExtension/*'
    - 'src/iOS.Widget/*'
    - src/watchOS/*

watchOS:
- changed-files:
  - any-glob-to-any-file:
    - src/watchOS/*